import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    q: "Does Refract upload my code?",
    a: "No. Everything runs locally. Your code never leaves your machine.",
  },
  {
    q: "What kind of projects does Refract support?",
    a: "Any JavaScript or TypeScript project — whether built manually or generated by tools like Lovable, Bolt, or v0.",
  },
  {
    q: "How is this different from a linter or Prettier?",
    a: "Linters flag issues. Refract fixes them. It modularizes components, rewrites types, renames variables, removes dead state, and generates documentation — automatically.",
  },
  {
    q: "Do I need to accept all changes?",
    a: "No. You review every transformation individually with a side-by-side diff preview. You decide what gets applied.",
  },
  {
    q: "What happens after I accept changes?",
    a: "Refract applies the selected transformations and opens a Pull Request with a fully documented changelog — ready to review and merge.",
  },
];


const FAQ = () => {
  return (
    <section id="faq" className="border-t border-border py-32">
      <div className="mx-auto max-w-3xl px-6">
        <div className="text-center">
          <p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">
            FAQ
          </p>
          <h2 className="mt-4 font-display text-4xl leading-tight tracking-tight text-balance sm:text-5xl">
            Questions, <em className="italic text-muted-foreground">answered</em>.
          </h2>
        </div>

        <Accordion type="single" collapsible className="mt-12 w-full">
          {faqs.map((f, i) => (
            <AccordionItem key={i} value={`item-${i}`} className="border-border">
              <AccordionTrigger className="text-left text-base hover:no-underline">
                {f.q}
              </AccordionTrigger>
              <AccordionContent className="text-muted-foreground">
                {f.a}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
};

export default FAQ;
