import { FeatureGridCard } from "@/components/ui/grid-feature-cards";
import { motion } from "motion/react";

const features = [
  {
    title: "Modularize components",
    description: "Detects oversized components and files generated by AI tools and extracts them into clean, reusable modules.",
  },
  {
    title: "Tailwind cleanup",
    description: "Groups repeated utility classes into consistent design patterns. No more 47-class divs scattered across your codebase.",
  },
  {
    title: "TypeScript-first",
    description: "Replaces generic 'any' types and plain JavaScript with real, inferred TypeScript types based on your actual data flow.",
  },
  {
    title: "Auto documentation",
    description: "Generates comments that explain why decisions were made — not just what the code does.",
  },
  {
    title: "AI-native refactors",
    description: "Designed from the ground up to understand the quirks and patterns of Bolt, v0, and other AI codegen tools.",
  },
  {
    title: "GitHub PRs",
    description: "Connect your repository via OAuth. Refract applies transformations and opens a Pull Request with a clean changelog.",
  }
];

export default function Features() {
  return (
    <section id="features" className="py-20 md:py-32">
      <div className="mx-auto max-w-7xl px-6 text-center">
        <motion.h2
          initial={{ filter: "blur(10px)", opacity: 0, y: 20 }}
          whileInView={{ filter: "blur(0px)", opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8 }}
          className="font-display text-4xl sm:text-5xl md:text-6xl tracking-tight"
        >
          Power. Speed. Control.
        </motion.h2>

        <div className="mt-16 grid gap-6 sm:grid-cols-2 lg:grid-cols-3 text-left">
          {features.map((feature, i) => (
            <FeatureGridCard key={i}>
              <h3 className="text-lg font-semibold text-foreground">
                {feature.title}
              </h3>
              <p className="mt-2 text-sm text-muted-foreground leading-relaxed">
                {feature.description}
              </p>
            </FeatureGridCard>
          ))}
        </div>
      </div>
    </section>
  );
}
