import { 
  Zap, 
  Activity, 
  Sparkles, 
  FileText, 
  Github, 
  CheckCircle2,
  LucideIcon 
} from 'lucide-react'
import { ReactNode } from 'react'
import { cn } from "@/lib/utils"
import { Card, CardHeader } from "@/components/ui/card"

const Features = () => {
    return (
        <section id="features" className="bg-zinc-50 py-16 md:py-32 dark:bg-transparent">
            <div className="mx-auto max-w-2xl px-6 lg:max-w-7xl">
                <div className="mx-auto grid gap-6 md:grid-cols-2 lg:grid-cols-3">
                    {/* Automatic Modularization */}
                    <FeatureCard>
                        <CardHeader className="pb-3">
                            <CardHeading
                                icon={Activity}
                                title="Automatic Modularization"
                                description="Detects oversized components and files generated by AI tools and extracts them into clean, reusable modules — without touching your logic."
                            />
                        </CardHeader>
                    </FeatureCard>

                    {/* Tailwind Cleanup */}
                    <FeatureCard>
                        <CardHeader className="pb-3">
                            <CardHeading
                                icon={Zap}
                                title="Tailwind Cleanup"
                                description="Groups repeated utility classes into consistent design patterns. No more 47-class divs scattered across your codebase."
                            />
                        </CardHeader>
                    </FeatureCard>

                    {/* Intelligent Typing */}
                    <FeatureCard>
                        <CardHeader className="pb-3">
                            <CardHeading
                                icon={Sparkles}
                                title="Intelligent Typing"
                                description="Replaces generic 'any' types and plain JavaScript with real, inferred TypeScript types based on your actual data flow."
                            />
                        </CardHeader>
                    </FeatureCard>

                    {/* Dead State Removal */}
                    <FeatureCard>
                        <CardHeader className="pb-3">
                            <CardHeading
                                icon={Activity}
                                title="Dead State Removal"
                                description="Identifies unnecessary useState hooks and redundant re-renders caused by AI-generated code and eliminates them."
                            />
                        </CardHeader>
                    </FeatureCard>

                    {/* Semantic Renaming */}
                    <FeatureCard>
                        <CardHeader className="pb-3">
                            <CardHeading
                                icon={FileText}
                                title="Semantic Renaming"
                                description="Replaces generic AI-generated names (data1, handleClick2, wrapper3) with names that reflect the actual business context."
                            />
                        </CardHeader>
                    </FeatureCard>

                    {/* Human Documentation */}
                    <FeatureCard>
                        <CardHeader className="pb-3">
                            <CardHeading
                                icon={FileText}
                                title="Human Documentation"
                                description="Generates comments that explain why decisions were made — not just what the code does. Built for the next developer who reads it."
                            />
                        </CardHeader>
                    </FeatureCard>

                    {/* Accessibility Fixes */}
                    <FeatureCard>
                        <CardHeader className="pb-3">
                            <CardHeading
                                icon={CheckCircle2}
                                title="Accessibility Fixes"
                                description="Ensures AI-generated UI components are functional for screen readers and keyboard navigation — not just visually correct."
                            />
                        </CardHeader>
                    </FeatureCard>

                    {/* GitHub / GitLab Integration */}
                    <FeatureCard>
                        <CardHeader className="pb-3">
                            <CardHeading
                                icon={Github}
                                title="GitHub / GitLab Integration"
                                description="Connect your repository via OAuth. Refract applies transformations and opens a Pull Request with a clean, documented changelog."
                            />
                        </CardHeader>
                    </FeatureCard>
                </div>
            </div>
        </section>
    )
}

interface FeatureCardProps {
    children: ReactNode
    className?: string
}

const FeatureCard = ({ children, className }: FeatureCardProps) => (
    <Card className={cn('group relative rounded-2xl shadow-zinc-950/5 overflow-hidden border-border', className)}>
        <CardDecorator />
        {children}
    </Card>
)

const CardDecorator = () => (
    <>
        <span className="border-primary/30 absolute -left-px -top-px block size-2 border-l-2 border-t-2"></span>
        <span className="border-primary/30 absolute -right-px -top-px block size-2 border-r-2 border-t-2"></span>
        <span className="border-primary/30 absolute -bottom-px -left-px block size-2 border-b-2 border-l-2"></span>
        <span className="border-primary/30 absolute -bottom-px -right-px block size-2 border-b-2 border-r-2"></span>
    </>
)

interface CardHeadingProps {
    icon: LucideIcon
    title: string
    description: string
}

const CardHeading = ({ icon: Icon, title, description }: CardHeadingProps) => (
    <div>
        <span className="text-primary flex items-center gap-2 text-xs font-semibold uppercase tracking-wider">
            <Icon className="size-4" />
            {title}
        </span>
        <p className="mt-4 text-xl font-semibold leading-tight">{description}</p>
    </div>
)

export default Features;
